### ISSUE TITLE
Plot Slice Error

### ISSUE THREAD

**Issue by EduardoSBastos** [joommf/help#2]
I am trying so make a Plot Slice on a project, and I get the error shown in the second annexed image. I have made a formula (first image) that returns "0" when the point is not within certain bounds. The problem disappears when I change the "0" to "1", but I can't see why it is the case, as the same method worked for the Tutorial. Could you shed some light on this problem?
  
![capture](https://cloud.githubusercontent.com/assets/28542390/25819723/3b2a4696-3405-11e7-91a3-82e02bb70454.PNG)

![capture](https://cloud.githubusercontent.com/assets/28542390/25819501/8b0dc6ac-3404-11e7-93ce-95ae74ebb62b.PNG)

Also, I would gladly send my code for it to be better evaluated, but it seems Github does not support the IPYNB format. Is there any other way I may send it? 

Thanks in advance for the help!

**Comment by fangohr** [comment]
Hi - thanks for the query. It is a little hard to say without seeing the whole program. (Are you saying you were not allowed to upload the notebook file?)

But we know there is a problem with the current `plot_slide()` function if the arrows to be drawn have zero x and zero y-component (if you are slicing a plane perpendicular to z, as in your example). So this could well be the problem here. Maybe Ms is zero for all positions, and thus the x and y components of the magnetisation are zero as well?

We are in the process of improving the plotting routines, but maybe the above is enough to help you here? Simply put, if my guessed analysis is right then either (i) the plotting is broken but your field is setup correctly, or (ii) the plotting is broken and the field is not set up as you like. The plotting will fail if the x and y components of all vectors are zero.

Please get back in touch if this doesn't help.
