### ISSUE TITLE
Vectorial sum of two df.Field

### ISSUE THREAD

**Issue by lleom582** [joommf/help#3]
hi
I have a problem summing two fields, a field of the form (Hx, 0, 0) uniform all over the volume, and a stray field (so a df.Field) of a permalloy sphere.
do you have some suggestions?

`Hstray = system.hamiltonian.demag.effective_field` is how I defined the stray field

I tried defining a function which, for a given point of the space given, returns the value of the fields summed, but after more than 7 hours running, I discarded this try.
I attach the function code.

thank you

![image](https://user-images.githubusercontent.com/58987741/71016458-788ffc80-20f5-11ea-984b-6c12a2f976d0.png)

**Comment by marijanbeg** [comment]
Hi @lleom582, thank you for your question. The reason why your function is very slow is because you are computing the stray field 3 times for each discretisation cell. The easiest solution would be to perform operations on arrays. For instance:

```
stray_field = system.hamiltonian.demag.effective_field
uniform_field = df.Field(mesh, value=(Hx, 0, 0))
sum_of_fields = df.Field(mesh, value=stray_field.array+uniform_field.array)
```

This assumes all three fields are derived on the same mesh. This could probably be simplified by overloading the addition operator for fields, but this is not a part of `discretisedfield` package.

I will close this issue, but please feel free to reopen it if anything does not make sense.
