### ISSUE TITLE
Updating oommfc

### ISSUE THREAD

**Issue by owliktuk** [joommf/help#4]
Hello,
I made tests and some of them failed (I am attaching file). Then, in the example "First OOMMFC notebook" at "In: 11" I get error:
`2017/5/16 15:29: Calling OOMMF (first_notebook/first_notebook.mif) ... [0.9s]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-06c529479cd5> in <module>()
      1 md = oc.MinDriver()
----> 2 md.drive(system)

/home/owliktuk/.local/lib/python3.5/site-packages/oommfc/drivers/driver.py in drive(self, system, **kwargs)
     34 
     35         if "derive" not in kwargs:
---> 36             self._update_system(system)
     37 
     38     def _makedir(self, system):

/home/owliktuk/.local/lib/python3.5/site-packages/oommfc/drivers/driver.py in _update_system(self, system)
     65     def _update_system(self, system):
     66         self._update_m(system)
---> 67         self._update_dt(system)
     68 
     69     def _update_m(self, system):

/home/owliktuk/.local/lib/python3.5/site-packages/oommfc/drivers/driver.py in _update_dt(self, system)
     89 
     90         # Update system's datatable.
---> 91         system.dt = oommfodt.OOMMFodt(last_odt_file).df
     92 
     93     def _filenames(self, system):

AttributeError: module 'oommfodt' has no attribute 'OOMMFodt'

`

Thanks for help in advance

[errors.txt](https://github.com/joommf/help/files/1004699/errors.txt)

**Comment by mb1a15** [comment]
Hi,

You got this error because we were in the middle of updating JOOMMF packages on PyPI when you installed `oommfc` (sorry about that). Therefore, just update `oommfc` by running:
```
python3 -m pip install --upgrade oommfc
```
in your terminal. Please note that for running tests in updated `oommfc`, you will also need to have `testpath` package. You can install it by running:
```
python3 -m pip install --upgrade pytest testpath
```

More detailed information you can find at:
1. Testing (http://oommfc.readthedocs.io/en/latest/ipynb/testing.html)
2. Updating (http://oommfc.readthedocs.io/en/latest/ipynb/updating.html)

Just let us know if you have any other questions.
