### ISSUE TITLE
install mumax3c

### ISSUE THREAD

**Issue by sty0305** [joommf/help#7]
I already successfully installed oommf and mumax3 on my Windows 64 bit pc and both of them runing well.

However, after i installed ubermag through conda, the oommfc is running well, while it did not install the mumax3c package and i could not finish the test.

Can you help me with this? Besides, is there a tutorial on mumax3 like oommfc?

Tingyu Su

**Comment by marijanbeg** [comment]
Hi Tingyu, I believe we addressed this question via email. Therefore, I will close this issue here.

Please note that all our packages now live in the Ubermag organisation. Therefore, for any questions you might have in the future, please raise an issue in https://github.com/ubermag/help repository.
